plugins {
    id "java-library"    
    id "com.diffplug.spotless" 
    id "com.gradleup.shadow"
}

spotless {
    kotlin {
        target "**/*.kt"
        ktlint()
    }

    java {
        target "**/*.java"
        googleJavaFormat()
    }
}

tasks.assemble.dependsOn tasks.shadowJar
tasks.build.dependsOn tasks.shadowJar
tasks.jar.dependsOn tasks.shadowJar

tasks.named("jar").configure {
    enabled = false
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

shadowJar {    
    exclude "META-INF/maven/org.eclipse.jgit/*/pom.xml"
    exclude "META-INF/maven/org.eclipse.jgit/*/pom.properties"
  
    archiveFileName.set("jgit-7.7.1.202607240634-r.jar")
    
    dependencies {
        exclude(dependency("org.slf4j:slf4j-api:2.1.0-alpha1"))
        exclude(dependency("org.slf4j:slf4j-simple:2.1.0-alpha1"))
        exclude(dependency("com.googlecode.javaewah:JavaEWAH:1.2.3"))
        exclude(dependency("commons-codec:commons-codec:1.22.0"))
    }
}

dependencies {
    implementation("org.eclipse.jgit:org.eclipse.jgit:7.7.1.202607240634-r")
    implementation("org.slf4j:slf4j-api:2.1.0-alpha1")
    implementation("org.slf4j:slf4j-simple:2.1.0-alpha1")
    implementation("com.googlecode.javaewah:JavaEWAH:1.2.3")
    implementation("commons-codec:commons-codec:1.22.0")
}